Repository EdurtIO/dbm, pull requests merged in 2021-09, with the labels that each got.

#29 [i18n] result message use i18n
  src/renderer/services/Common.js
Labels: i18n

#30 Update index.html
  docs/index.html
Labels: documentation

#36 Toni
  docs/docs/contribution.md
  docs/docs/reference/2.Get-Started-Query.md
  docs/docs/release/1.0.0-SNAPSHOT.md
  docs/docs/release/1.2.0-SNAPSHOT.md
  docs/docs/release/1.3.0-SNAPSHOT.md
  docs/docs/release/1.4.0.md
  src/renderer/i18n/zh_CN.js
  src/renderer/styles/sidebar.scss
  src/renderer/styles/transition.scss
  src/renderer/utils/JsonUtils.js
Labels: documentation, i18n

#38 Support for Lazy database engines
  src/renderer/i18n/en_US.js
  src/renderer/i18n/zh_CN.js
  src/renderer/utils/DatabaseEngineUtils.js
  src/renderer/utils/DatabaseUtils.js
  src/renderer/views/components/Database/Configuration/index.vue
  src/renderer/views/components/Database/Engine/Lazy/index.vue
  src/renderer/views/components/data/datasource/DataSource.vue
Labels: bug, enhancement

#39 [Bug] Fix build table not verified
  src/renderer/utils/ConvertUtils.js
  src/renderer/views/Data/Metadata/index.vue
  src/renderer/views/components/Table/Configuration/index.vue
  src/renderer/views/components/Table/Create/index.vue
  src/renderer/views/components/Table/Engines/HDFS/index.vue
  src/renderer/views/components/Table/Engines/Kafka/index.vue
Labels: bug
